name: Publish package to GitHub Packages
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@<latest-version>

      - name: Publish package
        uses: gradle/gradle-build-action@<latest-version>
        with:
          arguments: publish
        env:
          GITHUB_TOKEN: ${{ secrets.JAVA_TOKEN }}
